#!/bin/bash

set -e              # Willexit immediate if command exits with non-zero status
set -u              # Will print message if variable not set,
set -o pipefail     # Fail on a pipline like cmd1 | cmd2 | cmd3, rather then wait

exec 3>&1           # Make stdout available as fd 3 for the result
exec 1>&2           # Redirect all output to stderr for logging

source $(dirname $0)/common.sh

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

payload=$(mktemp $TMPDIR/helm-release-check.XXXXXX)
cat > $payload <&0

debug=$(jq -cr '.source.debug // 0' <  $payload)

if [[ "$debug" -eq "1" ]]; then
  set -x
fi

setuprepo

ref=$(jq -r '.version.ref' < $payload)

mkdir -p $destination
cd $destination
echo $ref > .version

jq -n "{
  version: {ref: \"$(echo $ref)\"},
  metadata: []
}" >&3