#!/bin/bash

set -e              # Willexit immediate if command exits with non-zero status
set -u              # Will print message if variable not set,
set -o pipefail     # Fail on a pipline like cmd1 | cmd2 | cmd3, rather then wait

exec 3>&1           # Make stdout available as fd 3 for the result
exec 1>&2           # Redirect all output to stderr for logging

export TMPDIR=${TMPDIR:-/tmp}

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 <path/to/source>"
  exit 1
fi

payload=$(mktemp $TMPDIR/helm-release-check.XXXXXX)

cat > $payload <&0

output=$(cat $payload | helm-chart-resource --action out --source $source --tmpdir $TMPDIR)

jq -n "$output" >&3