# github.com/go-task/task

version: '2'

tasks:
  build-rc:
    cmds:
      - docker build -t adgear/helm-chart-resource:{{.VERSION}} .
      - docker push adgear/helm-chart-resource:{{.VERSION}}
      - echo "adgear/helm-chart-resource:{{.VERSION}}" >> .cleanup
    vars:
      VERSION: {sh: date +%s}
  ensure:
    cmds:
      - dep ensure
  test:
    deps: [ensure]
    cmds:
      - go test $(go list ./... | grep -v mocks) -cover -v
  build:
    deps: [ensure]
    cmds:
      - go build -ldflags "-X main.version=`cat VERSION`" .
  mockgen:
    cmds:
      - for i in check in out; do mockgen -source=actions/$i.go -destination=mocks/mock_$i.go --package=mocks; done
      - mockgen -source=helm/helm.go -destination=mocks/mock_helm.go --package=mocks
      - mockgen -source=artifactory/artifactory.go -destination=mocks/mock_artifactory.go --package=mocks