platform: linux
image_resource:
  type: docker-image
  source:
    repository: adgear/helm-chart-resource
inputs:
- name: helm-chart-resource-pr
run:
  path: sh
  args:
    - -c
    - |
      #!/bin/bash
      cat helm-chart-resource-pr/ci/assets/check.json | bash ./helm-chart-resource-pr/check
      cat helm-chart-resource-pr/ci/assets/in.json | bash ./helm-chart-resource-pr/in etcd/
