platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.10.3-alpine3.7
inputs:
- name: helm-chart-resource-pr
run:
  path: sh
  args:
    - -c
    - |
      #!/bin/bash

      apk add --no-cache git
      go get -u github.com/golang/dep/cmd/dep    
      mkdir -p /go/src/github.com/adgear/helm-chart-resource/
      cp -pr helm-chart-resource-pr/* /go/src/github.com/adgear/helm-chart-resource/.
      cd /go/src/github.com/adgear/helm-chart-resource/
      dep ensure
      go test ./... -cover -v
