platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.15-alpine
inputs:
- name: helm-chart-resource-pr
outputs:
- name: coverage
run:
  path: sh
  args:
    - -c
    - |
      #!/bin/bash
      set -e

      apk add --no-cache --no-progress git
      go get -u github.com/golang/dep/cmd/dep
      go get -u -v github.com/go-task/task/cmd/task

      mkdir -p /go/src/github.com/adgear/helm-chart-resource/
      cp -pr helm-chart-resource-pr/* /go/src/github.com/adgear/helm-chart-resource/.
      test_path="$(pwd)/coverage"
      cd /go/src/github.com/adgear/helm-chart-resource/
      echo "\`\`\`console" > $test_path/tests.results
      task test >> $test_path/tests.results
      echo -n "\`\`\`" >> $test_path/tests.results

      cat $test_path/tests.results
